development:
  OCTAVADAY_DATABASE_NAME:
  OCTAVADAY_DATABASE_USERNAME:
  OCTAVADAY_DATABASE_PASSWORD:
  SECRET_KEY_BASE:

test:
  OCTAVADAY_DATABASE_NAME:
  OCTAVADAY_DATABASE_USERNAME:
  OCTAVADAY_DATABASE_PASSWORD:
  SECRET_KEY_BASE:

staging:
  OCTAVADAY_DATABASE_NAME:
  OCTAVADAY_DATABASE_USERNAME:
  OCTAVADAY_DATABASE_PASSWORD:
  SECRET_KEY_BASE: