# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['OCTAVADAY_DATABASE_USERNAME'] %>
  password: <%= ENV['OCTAVADAY_DATABASE_PASSWORD'] %>
  database: <%= ENV['OCTAVADAY_DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
